name: houzi_package
description: A new Flutter package.
version: 0.0.1
publish_to: none


environment:

  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  animate_icons: 2.0.0
  autocomplete_textfield: 2.0.1
  build_runner: 2.4.6
  cupertino_icons: 1.0.6
  dio: 5.3.3
  dio_cache_interceptor: 3.4.4
  #  dio_http_cache: 0.3.0
  expandable: 5.0.1
  fancy_shimmer_image: 2.0.3
  #  firebase_messaging: 13.0.2
  flutter_dialogs: 3.0.0
  flutter_staggered_grid_view: 0.4.0
  flutter_uploader: 3.0.0-beta.4

  flutter_widget_from_html: 0.14.6
  fluttertoast: 8.2.4
  flutter_local_notifications: 16.1.0
  location: 5.0.3
  geolocator: 10.1.0
  flutter_facebook_auth: 6.0.2
  html_unescape: 2.0.0
  hive_flutter: 1.1.0
  hive: 2.2.3
  hive_generator: 2.0.1
  image_picker: 1.0.4
  loading_gifs: 0.3.0
  loading_indicator: 3.1.1
  material_segmented_control: 5.0.0
  path_provider: 2.1.1
  pie_chart: 5.4.0
  provider: 6.1.1
  pull_to_refresh: 2.0.0
  shimmer: 3.0.0
  sliding_up_panel: 2.0.0+1
  smooth_page_indicator: 1.1.0
  timeago: 3.6.0
  toggle_switch: 2.1.0
  url_launcher: 6.2.1
  webview_flutter: 4.4.2
  shared_preferences: 2.2.2

  sign_in_with_apple: 5.0.0
  crypto: 3.0.3
  google_mobile_ads: 3.1.0
  app_tracking_transparency: 2.0.4
  carousel_slider: 4.2.1

  share_plus: 7.2.1
  google_maps_cluster_manager: 3.0.0+1

  intl_phone_number_input: 0.7.3+1
  intl_phone_field: 3.2.0

  firebase_analytics: 10.7.0
  firebase_auth: 4.14.0
  google_maps_flutter: 2.5.0
  google_sign_in: 6.1.6

  flutter_cache_manager: 3.3.1

  #****===== IMPORTANT =====****
  # use 2.2.11 if flutter version < 3.7.0
  # use 2.2.23 if 3.7.0 < flutter version < 3.10.2
  pinput: 3.0.1

  #****===== Updates =====****
  # for flutter 3.10.2
  path: 1.8.3
  #  intl: 0.18.0
  firebase_core: 2.22.0
  flutter_rating_bar: 4.0.1
  package_info_plus: 4.2.0
  in_app_purchase: 3.1.11

  #****===== Updates =====****
  # for flutter 3.13
  intl: 0.18.1

  fluster: 1.2.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.0


flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true